-- This file contains no migration.
-- Its purpose is solely to maintain the correct migration numbering for us,
-- as the actual first migration is handled by the Flyway baseline during migration execution,
-- so we need to start with V2.