name: 'test-db'
version: '3.8'

services:
  db:
    container_name: database_si
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_user
      POSTGRES_DB: database_si
    ports:
    - "5432:5432"