--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0 (Debian 17.0-1.pgdg120+1)
-- Dumped by pg_dump version 17.0 (Debian 17.0-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: rock_solid; Type: SCHEMA; Schema: -; Owner: db_user
--

CREATE SCHEMA rock_solid;


ALTER SCHEMA rock_solid OWNER TO db_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: article; Type: TABLE; Schema: rock_solid; Owner: db_user
--

CREATE TABLE rock_solid.article (
    id integer NOT NULL,
    article_name character varying(255),
    file_path character varying(255)
);

-- ALTER TABLE rock_solid.article ALTER COLUMN file SET DATA TYPE bytea USING file::bytea;

ALTER TABLE rock_solid.article OWNER TO db_user;

--
-- Name: article_id_seq; Type: SEQUENCE; Schema: rock_solid; Owner: db_user
--

ALTER TABLE rock_solid.article ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME rock_solid.article_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conference; Type: TABLE; Schema: rock_solid; Owner: db_user
--

CREATE TABLE rock_solid.conference (
    id integer NOT NULL,
    article_id integer NOT NULL,
    datefrom character varying(255),
    dateuntil character varying(255),
    form_id integer NOT NULL,
    year integer NOT NULL
);


ALTER TABLE rock_solid.conference OWNER TO db_user;

--
-- Name: conference_id_seq; Type: SEQUENCE; Schema: rock_solid; Owner: db_user
--

ALTER TABLE rock_solid.conference ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME rock_solid.conference_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: form; Type: TABLE; Schema: rock_solid; Owner: db_user
--

CREATE TABLE rock_solid.form (
    form_id integer NOT NULL,
    formcol character varying(255)
);


ALTER TABLE rock_solid.form OWNER TO db_user;

--
-- Name: form_form_id_seq; Type: SEQUENCE; Schema: rock_solid; Owner: db_user
--

ALTER TABLE rock_solid.form ALTER COLUMN form_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME rock_solid.form_form_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recenzent; Type: TABLE; Schema: rock_solid; Owner: db_user
--

CREATE TABLE rock_solid.recenzent (
    article_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE rock_solid.recenzent OWNER TO db_user;

--
-- Name: recenzent_article_id_seq; Type: SEQUENCE; Schema: rock_solid; Owner: db_user
--

ALTER TABLE rock_solid.recenzent ALTER COLUMN article_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME rock_solid.recenzent_article_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token; Type: TABLE; Schema: rock_solid; Owner: db_user
--

CREATE TABLE rock_solid.token (
    id integer NOT NULL,
    token character varying(255) NOT NULL,
    token_type character varying(255),
    expired boolean NOT NULL,
    revoked boolean NOT NULL,
    user_id bigint
);


ALTER TABLE rock_solid.token OWNER TO db_user;

--
-- Name: token_id_seq; Type: SEQUENCE; Schema: rock_solid; Owner: db_user
--

CREATE SEQUENCE rock_solid.token_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE rock_solid.token_id_seq OWNER TO db_user;

--
-- Name: token_id_seq; Type: SEQUENCE OWNED BY; Schema: rock_solid; Owner: db_user
--

ALTER SEQUENCE rock_solid.token_id_seq OWNED BY rock_solid.token.id;


--
-- Name: user; Type: TABLE; Schema: rock_solid; Owner: db_user
--

CREATE TABLE rock_solid."user" (
    id bigint NOT NULL,
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255) NOT NULL,
    article_id integer,
    role character varying(255)
);


ALTER TABLE rock_solid."user" OWNER TO db_user;

--
-- Name: user_id_seq; Type: SEQUENCE; Schema: rock_solid; Owner: db_user
--

CREATE SEQUENCE rock_solid.user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE rock_solid.user_id_seq OWNER TO db_user;

--
-- Name: user_id_seq; Type: SEQUENCE OWNED BY; Schema: rock_solid; Owner: db_user
--

ALTER SEQUENCE rock_solid.user_id_seq OWNED BY rock_solid."user".id;


--
-- Name: token id; Type: DEFAULT; Schema: rock_solid; Owner: db_user
--

ALTER TABLE ONLY rock_solid.token ALTER COLUMN id SET DEFAULT nextval('rock_solid.token_id_seq'::regclass);


--
-- Name: user id; Type: DEFAULT; Schema: rock_solid; Owner: db_user
--

ALTER TABLE ONLY rock_solid."user" ALTER COLUMN id SET DEFAULT nextval('rock_solid.user_id_seq'::regclass);


--
-- Data for Name: article; Type: TABLE DATA; Schema: rock_solid; Owner: db_user
--

COPY rock_solid.article (id, article_name) FROM stdin;
\.


--
-- Data for Name: conference; Type: TABLE DATA; Schema: rock_solid; Owner: db_user
--

COPY rock_solid.conference (id, article_id, datefrom, dateuntil, form_id, year) FROM stdin;
\.


--
-- Data for Name: form; Type: TABLE DATA; Schema: rock_solid; Owner: db_user
--

COPY rock_solid.form (form_id, formcol) FROM stdin;
\.


--
-- Data for Name: recenzent; Type: TABLE DATA; Schema: rock_solid; Owner: db_user
--

COPY rock_solid.recenzent (article_id, user_id) FROM stdin;
\.


--
-- Data for Name: token; Type: TABLE DATA; Schema: rock_solid; Owner: db_user
--

COPY rock_solid.token (id, token, token_type, expired, revoked, user_id) FROM stdin;
9	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjYsInN1YiI6IjEyMzRAZ21haWwuY29tIiwiaWF0IjoxNzMxMDA1Njg0LCJleHAiOjE3MzEwOTIwODR9.ktdGVEkMqRh3vk1Dih2Mw4rmk2HIONUZ3JKWSAvlBc0	BEARER	f	f	\N
6	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjQsInN1YiI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzMxMDA0MjAxLCJleHAiOjE3MzEwOTA2MDF9.7O6fBTvUk3xQhqvZZMScf4J_JWn-K8f2gP1eIRXqRbg	BEARER	f	f	\N
1	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIsInN1YiI6ImFAZ21haWwiLCJpYXQiOjE3MzA5OTA4OTMsImV4cCI6MTczMTA3NzI5M30.UtzdfPVbwjSfOpM5uJYW_WHTgVcjbXTfypYePVdAXE0	BEARER	t	t	\N
2	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIsInN1YiI6ImFAZ21haWwiLCJpYXQiOjE3MzA5OTA5MzMsImV4cCI6MTczMTA3NzMzM30.YM_GtNkLxwubJC3kTVRg35kgOL0g791UmpH-TBwYUZA	BEARER	f	f	\N
7	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjUsInN1YiI6IjEyMzRAZ21haWwuY29tIiwiaWF0IjoxNzMxMDA0MjU0LCJleHAiOjE3MzEwOTA2NTR9.fdhGQUUw9p6EsZb6ic69zL8PgLkVtnD1pvXaJHogXiI	BEARER	t	t	\N
8	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjUsInN1YiI6IjEyMzRAZ21haWwuY29tIiwiaWF0IjoxNzMxMDA0NDkzLCJleHAiOjE3MzEwOTA4OTN9.CjUJsIVOJrkA5QDJNb2GGNI0gtDo8DMqJ9vxPS76DkQ	BEARER	f	f	\N
3	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjMsInN1YiI6ImFsZXhrb0B1a2Yuc2siLCJpYXQiOjE3MzA5OTA5NjksImV4cCI6MTczMTA3NzM2OX0.SQ_Fm76HXmunpQglxW2927pAATskVVtjovBu0f1Kz0g	BEARER	t	t	\N
4	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjMsInN1YiI6ImFsZXhrb0B1a2Yuc2siLCJpYXQiOjE3MzA5OTA5OTEsImV4cCI6MTczMTA3NzM5MX0.wzv0gzgOAgOq9W_BnL1iOoEI1TEhvwiGKPnUGzvLxgI	BEARER	t	t	\N
5	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjMsInN1YiI6ImFsZXhrb0B1a2Yuc2siLCJpYXQiOjE3MzA5OTEwOTgsImV4cCI6MTczMTA3NzQ5OH0.kvAy5FpeWCPWB_CaBlmlZWxKUzd0fPOj67bZTdoYUik	BEARER	f	f	\N
10	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjcsInN1YiI6InRlc3RpY2VrQGdtYWlsLmNvbSIsImlhdCI6MTczMjA5OTAxMCwiZXhwIjoxNzMyMTg1NDEwfQ.9yd3Y6PEFvJhfpKyY7CGoJDWtPxetPdL_Gg6YRRov3M	BEARER	t	t	7
11	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjcsInN1YiI6InRlc3RpY2VrQGdtYWlsLmNvbSIsImlhdCI6MTczMjA5OTAyMCwiZXhwIjoxNzMyMTg1NDIwfQ.Yb6EdZOPMpDZSvJiKeCI2McJtm3aGwB5GCjYOL-oqGc	BEARER	t	t	7
13	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjcsInN1YiI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTczMzIyMTU4NiwiZXhwIjoxNzMzMzA3OTg2fQ.skVWDnT2RKHkoJoKvITwjxzQsStfsWyEGUq4Y8iaWfA	BEARER	t	t	7
15	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEwLCJzdWIiOiJ0QGdtYWlsLmNvbSIsImlhdCI6MTczMzI5OTQ3NCwiZXhwIjoxNzMzMzg1ODc0fQ.OmnIsAKeNPZUESmY7xcge0zPur7TACLX4-WghrlqYPI	BEARER	f	f	10
14	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjcsInN1YiI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTczMzI1OTIwOCwiZXhwIjoxNzMzMzQ1NjA4fQ.oNyU-BA0x40khaCYcPFJ_qfJU0h2S5jq9UU06xqDERU	BEARER	t	t	7
16	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjcsInN1YiI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTczMzI5OTQ5NCwiZXhwIjoxNzMzMzg1ODk0fQ.u1IBnH-cwyQ6XZuG1-lYlMJOr3svm97qTqU_r2tuKzA	BEARER	t	t	7
12	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjgsInN1YiI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzMzMjIxNTI5LCJleHAiOjE3MzMzMDc5Mjl9.G_7--bwYMmkUenl_xy7NCmWDZgrmAVxFBVR0Gtmq61M	BEARER	t	t	8
17	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjcsInN1YiI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTczMzI5OTUxOCwiZXhwIjoxNzMzMzg1OTE4fQ.qj7hgz4dgLFTg1HVw4uCkpM5Yz4e4J5V1XiI1LjzgVE	BEARER	t	t	7
18	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjgsInN1YiI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzMzMjk5NTQ3LCJleHAiOjE3MzMzODU5NDd9.d_2oq61b6262l8EAnkBL9p-QyZ8DI8WjgEn2c-OaeMw	BEARER	t	t	8
20	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjgsInN1YiI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzMzMjk5NTgwLCJleHAiOjE3MzMzODU5ODB9.ndyuWB1kbqGO_hhmNzFK0Aa6O-_Jt2qkRBvHNR4339k	BEARER	f	f	8
19	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjcsInN1YiI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTczMzI5OTU2MCwiZXhwIjoxNzMzMzg1OTYwfQ.2rszT4sSHr9avuVXxp-8xLYAvd0YR7OGNiRRAEYZi4I	BEARER	t	t	7
21	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjcsInN1YiI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTczMzI5OTY1OSwiZXhwIjoxNzMzMzg2MDU5fQ.tcqi_ltBwp9gogyPULxmXcyHEgT-hcmeCsK0C3Sn8n0	BEARER	t	t	7
22	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjcsInN1YiI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTczMzMwNDAyNiwiZXhwIjoxNzMzMzkwNDI2fQ.HeA77Xd83I74OPj0TwEmgE1Qnlp3AVzIRDm-Sxk9EGU	BEARER	t	t	7
24	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjExLCJzdWIiOiJ0ZXN0QHN0dWRlbnQuY29tIiwiaWF0IjoxNzMzMzA0NjQ4LCJleHAiOjE3MzMzOTEwNDh9.NVGzpShmQ5NiYgo2MCaEr7KwTCqs3u2GsrrAaOAFgD8	BEARER	t	t	\N
23	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjcsInN1YiI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTczMzMwNDA3OCwiZXhwIjoxNzMzMzkwNDc4fQ.pGpd_seJdLi6Xo70F2ph63APcTu6RJdvbdU7hwu5gYg	BEARER	t	t	7
26	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEyLCJzdWIiOiJhQGFkbWluLmNvbSIsImlhdCI6MTczMzMwNTM3OSwiZXhwIjoxNzMzMzkxNzc5fQ.G7vnLa8WOIDQVRAAPYudYIw9eieKDsHBGo3KbQrVAq0	BEARER	t	t	\N
27	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEyLCJzdWIiOiJhQGFkbWluLmNvbSIsImlhdCI6MTczMzMwNTM4NiwiZXhwIjoxNzMzMzkxNzg2fQ.ybDT6aFxDtOPwglYAUjOSar82bKr1XFerIGM9wF5df4	BEARER	f	f	\N
28	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjcsInN1YiI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTczMzMwNTQxOSwiZXhwIjoxNzMzMzkxODE5fQ.L536dJGWC8dr5smfj_KYCAJ9l9u3lbfxgpcQGzi3-i4	BEARER	t	t	7
30	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjcsInN1YiI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTczMzMwOTE5MiwiZXhwIjoxNzMzMzk1NTkyfQ.PhOCuw2ioB3JgU_zju1U_s0q1M9TGgKH05ppQ3Q-wk0	BEARER	f	f	7
25	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjExLCJzdWIiOiJ0ZXN0QHN0dWRlbnQuY29tIiwiaWF0IjoxNzMzMzA0Njg2LCJleHAiOjE3MzMzOTEwODZ9.cKwy3UgzL6g5aX_5TzCPg-sD5GzzEImBpQuXU_eaM3s	BEARER	t	t	\N
29	eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjExLCJzdWIiOiJ0ZXN0QHN0dWRlbnQuY29tIiwiaWF0IjoxNzMzMzA5MTIyLCJleHAiOjE3MzMzOTU1MjJ9.iv8L4lHScxoSIIlllDS0c_yFr3xsbrUBFes1VH5DOXw	BEARER	f	f	\N
\.


--
-- Data for Name: user; Type: TABLE DATA; Schema: rock_solid; Owner: db_user
--

COPY rock_solid."user" (id, email, first_name, last_name, password, article_id, role) FROM stdin;
8	test@gmail.com	lala	hoho	$2a$10$Xl77JT/iyE.ZBuUn.j/emOu2LTvOkbLPI3RTtoCew22XM9lVc9x8.	0	REVIEWER
7	admin@admin.com	admin	admin	$2a$10$186AuKz6ziICvDX/JI9Yu.7UEbYCpEUHFOepjTk7TWoD5k9T2Tknu	0	ADMIN
10	t@gmail.com	dalsi test	testovaci test	$2a$10$Xl77JT/iyE.ZBuUn.j/emOu2LTvOkbLPI3RTtoCew22XM9lVc9x8.	0	STUDENT
\.


--
-- Name: article_id_seq; Type: SEQUENCE SET; Schema: rock_solid; Owner: db_user
--

SELECT pg_catalog.setval('rock_solid.article_id_seq', 1, false);


--
-- Name: conference_id_seq; Type: SEQUENCE SET; Schema: rock_solid; Owner: db_user
--

SELECT pg_catalog.setval('rock_solid.conference_id_seq', 1, false);


--
-- Name: form_form_id_seq; Type: SEQUENCE SET; Schema: rock_solid; Owner: db_user
--

SELECT pg_catalog.setval('rock_solid.form_form_id_seq', 1, false);


--
-- Name: recenzent_article_id_seq; Type: SEQUENCE SET; Schema: rock_solid; Owner: db_user
--

SELECT pg_catalog.setval('rock_solid.recenzent_article_id_seq', 1, false);


--
-- Name: token_id_seq; Type: SEQUENCE SET; Schema: rock_solid; Owner: db_user
--

SELECT pg_catalog.setval('rock_solid.token_id_seq', 30, true);


--
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: rock_solid; Owner: db_user
--

SELECT pg_catalog.setval('rock_solid.user_id_seq', 12, true);


--
-- Name: article article_pkey; Type: CONSTRAINT; Schema: rock_solid; Owner: db_user
--

ALTER TABLE ONLY rock_solid.article
    ADD CONSTRAINT article_pkey PRIMARY KEY (id);


--
-- Name: conference conference_pkey; Type: CONSTRAINT; Schema: rock_solid; Owner: db_user
--

ALTER TABLE ONLY rock_solid.conference
    ADD CONSTRAINT conference_pkey PRIMARY KEY (id);


--
-- Name: form form_pkey; Type: CONSTRAINT; Schema: rock_solid; Owner: db_user
--

ALTER TABLE ONLY rock_solid.form
    ADD CONSTRAINT form_pkey PRIMARY KEY (form_id);


--
-- Name: recenzent recenzent_pkey; Type: CONSTRAINT; Schema: rock_solid; Owner: db_user
--

ALTER TABLE ONLY rock_solid.recenzent
    ADD CONSTRAINT recenzent_pkey PRIMARY KEY (article_id);


--
-- Name: token token_pkey; Type: CONSTRAINT; Schema: rock_solid; Owner: db_user
--

ALTER TABLE ONLY rock_solid.token
    ADD CONSTRAINT token_pkey PRIMARY KEY (id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: rock_solid; Owner: db_user
--

ALTER TABLE ONLY rock_solid."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: token token_user_id_fkey; Type: FK CONSTRAINT; Schema: rock_solid; Owner: db_user
--

ALTER TABLE ONLY rock_solid.token
    ADD CONSTRAINT token_user_id_fkey FOREIGN KEY (user_id) REFERENCES rock_solid."user"(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

